# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee6212bcbd9649d3d1c9af0f02166a2af162a454901bf61bfb5b7d972448bf405b824a874283c37f2ca5742b328ffe0b0ea5075c8bd1929c976cc45a6eb0f7c0

test:
  secret_key_base: 0ceca43e5d7901e97d0dc4549d7140d74b7e225ec8ac4d0f38e95d00a20b45876f6f51db7b236e51688538c54a559d6e7e8afed80eb8c58fd965e8d772d3457d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
